### ISSUE TITLE
dns pods that were running on the not-ready nodes should get deleted from the api server

### ISSUE THREAD

**Issue by abhat** [glennswest/podsupervisor#1]
One of the things we were trying to address with this podsupervisor was to delete the dns pods (that were scheduled on the nodes that went to NotReady) from the api server. The podsuper-nodecleanup.sh seems to not account for that.

**Comment by glennswest** [comment]
Already added it to list - while I believe deleting the source pods will cause dns updates across its simple to add the kill of the dnsSent from my iPhoneOn 27 Sep 2022, at 4:25 PM, Aniket Bhat ***@***.***> wrote:﻿
One of the things we were trying to address with this podsupervisor was to delete the dns pods (that were scheduled on the nodes that went to NotReady) from the api server. The podsuper-nodecleanup.sh seems to not account for that.

**Comment by glennswest** [comment]
Resolved.

**Comment by glennswest** [comment]
Added the enhancement to code/doc and tested.
